version: "3"
services:
  api:
    build: ./api-websocket
    container_name: go
    working_dir: /app
    volumes:
      - ./api-websocket:/app
    ports:
      - 8080:8081
    networks:
      - app-network
volumes:
    data:
      driver: local
networks:
  app-network:
    driver: bridge