version: "3"
services:
  api:
    build: ./api-websocket
    container_name: go
    working_dir: /app
    volumes:
      - ./api-websocket:/app
    ports:
      - 8080:8081
    networks:
      - app-network
  mongo:
    container_name: mongo
    volumes:  
      - dbdata:/data/db   
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network
    ports:
      - 27017:27017
    networks:
      - app-network
  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - app-network
volumes:
    dbdata:
networks:
  app-network:
    driver: bridge